Add support for ARM64 images
- Updated upload-model-to-s3.yml and upload-model-to-dockerhub.yml to follow
same workflow as later models (e.g. eos4e40)
- Copied over upload-ersilia-pack.yml and upload-bentoml.yml from eos4e40 repo
as part of workflow update.
- Updated metadata to include ARM64 architectures

diff --git a/.github/workflows/upload-model-to-s3.yml b/.github/workflows/upload-model-to-s3.yml
--- a/.github/workflows/upload-model-to-s3.yml
+++ b/.github/workflows/upload-model-to-s3.yml
@@ -45,8 +45,18 @@ jobs:
           conda init
           python -m pip install git+https://github.com/ersilia-os/ersilia.git
                   
+      - name: Check metadata file
+        id: checkMetadata
+        continue-on-error: true
+        run: |
+          if [[ ! -f metadata.yml ]]; then
+            echo "metadata.yml file not found"
+            exit 1
+          fi
+
       - name: Update Metadata JSON file with DockerHub info
-        id: UpdateMetadata
+        if: steps.checkMetadata.outcome == 'failure'
+        id: UpdateMetadataJSON
         run: |
           python3 -c "
           import json
@@ -55,6 +65,19 @@ jobs:
           data['S3'] = 'https://ersilia-models-zipped.s3.eu-central-1.amazonaws.com/{0}.zip'.format(data['Identifier'])
           with open('metadata.json', 'w') as f:
              json.dump(data, f, indent=4)
+          "
+
+      - name: Update Metadata YAML file with DockerHub info
+        if: steps.checkMetadata.outcome == 'success'
+        id: UpdateMetadataYAML
+        run: |
+          python3 -c "
+          import yaml
+          with open('metadata.yml', 'r') as f:
+             data = yaml.safe_load(f)
+          data['S3'] = 'https://ersilia-models-zipped.s3.eu-central-1.amazonaws.com/{0}.zip'.format(data['Identifier'])
+          with open('metadata.yml', 'w') as f:
+             yaml.dump(data, f, default_flow_style=False, sort_keys=False)
           "
           
       - name: Commit and push changes done to the Metadata JSON file
@@ -77,11 +100,25 @@ jobs:
           AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
         run: |
           source activate
+          pip install requests pyairtable
           echo "Updating metadata to AirTable looking at owner: $USER_NAME"
-          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_metadata_to_airtable.py
-          python3 update_metadata_to_airtable.py $USER_NAME $REPO_NAME $BRANCH $AIRTABLE_API_KEY
-          rm update_metadata_to_airtable.py
-  
+          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/airtableops.py
+          python3 airtableops.py airtable-update --user $USER_NAME --repo $REPO_NAME --branch $BRANCH --api-key $AIRTABLE_API_KEY
+          rm airtableops.py
+
+      - name: sync metadata to S3 JSON
+        id: sync-metadata-to-s3
+        env:
+          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          source activate
+          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/convert_airtable_to_json.py
+          pip install boto3 requests pyairtable
+          python convert_airtable_to_json.py $AIRTABLE_API_KEY $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
+          rm convert_airtable_to_json.py
+          
       - name: Update README file
         id: update-readme-file
         env:
@@ -89,9 +126,9 @@ jobs:
         run: |
           source activate
           echo "Updating README file with AirTable metadata for model: $MODEL_ID"
-          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_readme_from_airtable.py
-          python3 update_readme_from_airtable.py $MODEL_ID .
-          rm update_readme_from_airtable.py
+          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/airtableops.py
+          python3 airtableops.py readme-update --repo $MODEL_ID --path .
+          rm airtableops.py
           less README.md
 
       - name: Commit and push changes done to the README file
